## **Welcome to Feature Engineering!**
**Topic**: The Bangladesh World Cup 2026 Streaming Crisis. Users bought subscriptions for Bioscope and Toffee, but thousands faced OTP failures, login crashes, and massive buffering. Our goal: engineer features to predict who uninstalled the app (Target_Uninstall).

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
 #load the dataset
df  = pd.read_csv('bd_wc2026_streaming_churn.csv')
df.head(20)

,Phone_Prefix,Platform,Subscription_Plan,Match_Date,Login_Status,Buffer_Count,Watch_Minutes,App_Rating,Target_Uninstall
0,13,Toffee,Weekly_Pass,2026-06-29,Success,5.0,101.0,NaN,0
1,15,Bioscope,Weekly_Pass,2026-06-16,Stuck_at_Number_Screen,1.0,7.0,1.0,1
2,16,Bioscope,WC_Premium,2026-07-01,Buffer_Timeout,2.0,11.0,2.0,0
3,18,Toffee,Daily_Pass,2026-07-04,Stuck_at_Number_Screen,1.0,0.0,1.0,1
4,17,Toffee,Weekly_Pass,2026-07-01,Success,12.0,97.0,4.0,1
5,17,Toffee,WC_Premium,2026-07-05,OTP_Failed,0.0,4.0,1.0,1
6,17,Toffee,WC_Premium,2026-06-27,Success,5.0,104.0,NaN,0
7,19,Bioscope,Weekly_Pass,2026-07-08,Stuck_at_Number_Screen,1.0,0.0,2.0,1
8,18,Bioscope,Weekly_Pass,2026-07-08,Success,5.0,87.0,5.0,0
9,16,Toffee,Daily_Pass,2026-06-16,OTP_Failed,1.0,5.0,NaN,1
10,17,Toffee,Weekly_Pass,2026-07-03,OTP_Failed,0.0,5.0,1.0,1
11,15,Toffee,WC_Premium,2026-06-12,OTP_Failed,1.0,1.0,1.0,1
12,19,Other_Partner,WC_Premium,2026-06-16,Buffer_Timeout,2.0,7.0,1.0,1
13,17,Toffee,WC_Premium,2026-06-27,Success,3.0,90.0,NaN,0
14,17,Bioscope,Daily_Pass,2026-07-10,Success,1.0,63.0,4.0,0
15,17,Bioscope,WC_Premium,2026-06-29,Success,1.0,56.0,4.0,0
16,17,Bioscope,Daily_Pass,2026-07-10,Success,9.0,91.0,5.0,0
17,18,Bioscope,Daily_Pass,2026-06-28,Success,7.0,66.0,NaN,0
18,13,Toffee,Weekly_Pass,2026-07-03,Success,2.0,90.0,5.0,0
19,17,Bioscope,Daily_Pass,2026-06-21,Stuck_at_Number_Screen,6.0,7.0,1.0,1

In [ ]:
df.shape

(15000, 9)

In [ ]:
df.head(600).tail(15)

,Phone_Prefix,Platform,Subscription_Plan,Match_Date,Login_Status,Buffer_Count,Watch_Minutes,App_Rating,Target_Uninstall
585,17,Toffee,Weekly_Pass,2026-07-01,Success,5.0,122.0,4.0,0
586,17,Toffee,WC_Premium,2026-06-29,Stuck_at_Number_Screen,0.0,8.0,NaN,1
587,17,Toffee,Weekly_Pass,2026-06-29,Buffer_Timeout,0.0,6.0,1.0,0
588,17,Toffee,WC_Premium,2026-06-15,Stuck_at_Number_Screen,1.0,0.0,NaN,1
589,17,Toffee,WC_Premium,2026-06-12,OTP_Failed,0.0,13.0,1.0,1
590,17,Bioscope,Daily_Pass,2026-06-11,Stuck_at_Number_Screen,1.0,0.0,1.0,1
591,18,Bioscope,Daily_Pass,2026-06-15,OTP_Failed,6.0,9.0,2.0,0
592,17,Bioscope,Daily_Pass,2026-06-20,Success,1.0,105.0,4.0,0
593,17,Bioscope,WC_Premium,2026-07-10,Success,3.0,103.0,5.0,0
594,19,Toffee,WC_Premium,2026-07-09,Success,6.0,56.0,4.0,0
595,18,Toffee,Weekly_Pass,2026-06-27,OTP_Failed,0.0,4.0,1.0,0
596,16,Toffee,Weekly_Pass,2026-07-10,OTP_Failed,1.0,4.0,2.0,1
597,17,Bioscope,WC_Premium,2026-06-24,Success,10.0,82.0,4.0,0
598,17,Bioscope,Daily_Pass,2026-06-15,OTP_Failed,2.0,0.0,1.0,1
599,17,Toffee,Daily_Pass,2026-06-14,OTP_Failed,0.0,4.0,1.0,1

In [ ]:
df.sample(n=10)

,Phone_Prefix,Platform,Subscription_Plan,Match_Date,Login_Status,Buffer_Count,Watch_Minutes,App_Rating,Target_Uninstall
2140,19,Bioscope,Weekly_Pass,2026-06-22,Success,6.0,54.0,3.0,0
715,14,Bioscope,WC_Premium,2026-06-29,Buffer_Timeout,1.0,12.0,NaN,0
4977,17,Toffee,Weekly_Pass,2026-06-27,Buffer_Timeout,1.0,1.0,NaN,0
9322,18,Toffee,Weekly_Pass,2026-06-28,Success,9.0,96.0,NaN,0
4596,16,Other_Partner,WC_Premium,2026-07-09,Success,3.0,111.0,4.0,0
449,17,Toffee,Weekly_Pass,2026-06-21,Success,3.0,99.0,5.0,0
5307,13,Toffee,Weekly_Pass,2026-06-23,OTP_Failed,3.0,8.0,2.0,1
3955,19,Other_Partner,Weekly_Pass,2026-06-16,Success,8.0,76.0,5.0,0
7261,17,Bioscope,WC_Premium,2026-06-30,Success,0.0,79.0,NaN,0
1342,19,Bioscope,Daily_Pass,2026-06-14,Success,10.0,91.0,4.0,0

In [ ]:
df['Phone_Prefix'].unique()

array([13, 15, 16, 18, 17, 19, 14])

In [ ]:
df.Phone_Prefix.unique()

array([13, 15, 16, 18, 17, 19, 14])

In [ ]:
df.isnull().sum()

Phone_Prefix            0
Platform                0
Subscription_Plan       0
Match_Date              0
Login_Status            0
Buffer_Count            0
Watch_Minutes           0
App_Rating           2984
Target_Uninstall        0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = 'median')
df['App_Rating'] = imputer.fit_transform(df[['App_Rating']])

In [ ]:
df.isnull().sum()

Phone_Prefix         0
Platform             0
Subscription_Plan    0
Match_Date           0
Login_Status         0
Buffer_Count         0
Watch_Minutes        0
App_Rating           0
Target_Uninstall     0
dtype: int64

In [ ]:
df['Match_Date'] = pd.to_datetime(df['Match_Date'])

In [ ]:
df['Match_DayOfWeek'] = df['Match_Date'].dt.day_name()
df = df.drop(columns= ['Match_Date'])

In [ ]:
df.head()

,Phone_Prefix,Platform,Subscription_Plan,Login_Status,Buffer_Count,Watch_Minutes,App_Rating,Target_Uninstall,Match_DayOfWeek
0,13,Toffee,Weekly_Pass,Success,5.0,101.0,3.0,0,Monday
1,15,Bioscope,Weekly_Pass,Stuck_at_Number_Screen,1.0,7.0,1.0,1,Tuesday
2,16,Bioscope,WC_Premium,Buffer_Timeout,2.0,11.0,2.0,0,Wednesday
3,18,Toffee,Daily_Pass,Stuck_at_Number_Screen,1.0,0.0,1.0,1,Saturday
4,17,Toffee,Weekly_Pass,Success,12.0,97.0,4.0,1,Wednesday

In [ ]:
df['Buffer_Per_Minute'] = df['Buffer_Count'] / (df['Watch_Minutes']+1)

In [ ]:
df.head()

,Phone_Prefix,Platform,Subscription_Plan,Login_Status,Buffer_Count,Watch_Minutes,App_Rating,Target_Uninstall,Match_DayOfWeek,Buffer_Per_Minute
0,13,Toffee,Weekly_Pass,Success,5.0,101.0,3.0,0,Monday,0.049020
1,15,Bioscope,Weekly_Pass,Stuck_at_Number_Screen,1.0,7.0,1.0,1,Tuesday,0.125000
2,16,Bioscope,WC_Premium,Buffer_Timeout,2.0,11.0,2.0,0,Wednesday,0.166667
3,18,Toffee,Daily_Pass,Stuck_at_Number_Screen,1.0,0.0,1.0,1,Saturday,1.000000
4,17,Toffee,Weekly_Pass,Success,12.0,97.0,4.0,1,Wednesday,0.122449

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
ord_enc = OrdinalEncoder(categories = [['Daily_Pass', 'Weekly_Pass', 'WC_Premium']])
df['Subscription_Plan'] = ord_enc.fit_transform(df[['Subscription_Plan']])

In [ ]:
df = pd.get_dummies(df, columns = ['Platform', 'Match_DayOfWeek', 'Login_Status'], drop_first= True, dtype =int)

In [ ]:
!pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.12/dist-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)

In [ ]:
import category_encoders as ce

target_enc = ce.TargetEncoder(cols =['Phone_Prefix'])
df['Phone_Prefix'] = target_enc.fit_transform(df['Phone_Prefix'], df['Target_Uninstall'])

In [ ]:
from sklearn.preprocessing import StandardScaler, RobustScaler

scaler = RobustScaler()
df['Watch_Minutes'] = scaler.fit_transform(df[['Watch_Minutes']])
df['Buffer_Count'] = scaler.fit_transform(df[['Buffer_Count']])
df['Buffer_Per_Minute'] = scaler.fit_transform(df[['Buffer_Per_Minute']])
df['App_Rating'] = scaler.fit_transform(df[['App_Rating']])

In [ ]:
df.head()

,Phone_Prefix,Subscription_Plan,Buffer_Count,Watch_Minutes,App_Rating,Target_Uninstall,Buffer_Per_Minute,Platform_Other_Partner,Platform_Toffee,Match_DayOfWeek_Monday,Match_DayOfWeek_Saturday,Match_DayOfWeek_Sunday,Match_DayOfWeek_Thursday,Match_DayOfWeek_Tuesday,Match_DayOfWeek_Wednesday,Login_Status_OTP_Failed,Login_Status_Stuck_at_Number_Screen,Login_Status_Success
0,0.324201,1.0,0.333333,0.375000,0.000000,0,-0.226589,0,1,1,0,0,0,0,0,0,0,1
1,0.369919,1.0,-0.333333,-0.693182,-0.666667,1,0.117191,0,0,0,0,0,0,1,0,0,1,0
2,0.332404,2.0,-0.166667,-0.647727,-0.333333,0,0.305716,0,0,0,0,0,0,0,1,0,0,0
3,0.310184,0.0,-0.333333,-0.772727,-0.666667,1,4.076207,0,1,0,1,0,0,0,0,0,1,0
4,0.317454,1.0,1.500000,0.329545,0.333333,1,0.105649,0,1,0,0,0,0,0,1,0,0,1

##**Rule 1 of ML: Never evaluate your model on the data it trained on.**
##**Rule 2 of ML: Never let information from your test set "leak" into your training set.**

In [ ]:
#feature
X = df.drop(columns = ['Target_Uninstall'])

#label
y = df['Target_Uninstall']

In [ ]:
y.value_counts()

Target_Uninstall
0    10172
1     4828
Name: count, dtype: int64

In [ ]:
!pip install imbalanced.learn

Requirement already satisfied: imbalanced.learn in /usr/local/lib/python3.12/dist-packages (0.14.2)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced.learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced.learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced.learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from imbalanced.learn) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced.learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced.learn) (3.6.0)

In [ ]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state= 42)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [ ]:
X_train_smote, y_train_smote = smote.fit_resample(X_train,y_train)

In [ ]:
from imblearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report

In [ ]:
pipeline = Pipeline(
    [
        ('scaler', RobustScaler()),
        ('smote', SMOTE(random_state=42)),
        ('model', RandomForestClassifier(random_state=42))
    ]
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(pipeline, X_train, y_train, cv=cv, scoring='accuracy')

# print("Cross-validation scores:", {scores} )

In [ ]:
pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.91      0.91      2543
           1       0.81      0.81      0.81      1207

    accuracy                           0.88      3750
   macro avg       0.86      0.86      0.86      3750
weighted avg       0.88      0.88      0.88      3750